const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_TO_CARTS: "ADD_TO_CARTS",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_CART :"INCREMENT_CART",
  DECREMENT_CART: "DECREMENT_CART",
  POST_ORDER: "POST_ORDER",
};
export default ActionTypes;
